# Generated by Django 5.1.4 on 2025-01-06 19:34

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models
import feedparser
import re
import os

class Migration(migrations.Migration):

    rss_data = "/Users/tpl1122_1/Desktop/projects/wtnv/episodes/rss-feed.txt"

    with open(rss_data, 'r') as file_obj:
        first_char = file_obj.read(1)

    if not first_char:
        wtnv_rss_url = "https://feeds.nightvalepresents.com/welcometonightvalepodcast"
        feed = feedparser.parse(wtnv_rss_url)
        file = open(rss_data, "a")
        file.write(str(feed))
        file.close()
    else:
        print("text file created already.")

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodeIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
