# Generated by Django 5.1.4 on 2025-01-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episodeindexpage",
            name="intro",
        ),
    ]
