# Generated by Django 5.1.4 on 2025-01-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0002_episodepage_remove_episodeindexpage_intro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episodepage",
            name="summary",
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
