# Generated by Django 5.1.3 on 2025-01-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0003_alter_episodepage_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodepage",
            name="image_url",
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
